project/blog/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import PostListView, PostDetailView, LikeDislike, Comment, bookmarks, Penulis, archives, AllPost, Tags, search

app_name = "blog"

urlpatterns = [
    path('', AllPost.as_view(), name='home'),
    path('videos/', TemplateView.as_view(template_name='blog/videos.html'), name='videos'),
    path('post/<slug>/', PostDetailView.as_view(), name='detail'),
    path('tags/<str:tag>', Tags.as_view(), name='tag'),
    path('search/',search, name='search' ),
    path('requirement/<int:post_id>/<str:opinion>', LikeDislike.as_view(), name='like_dislike'),
    path('comment/<str:slug>', Comment.as_view(), name='comment'),
    path('video-detail/', TemplateView.as_view(template_name='blog/single-video.html'), name='video-detail'),
    path('bookmarks/<int:id>', bookmarks, name='bookmarks'),
    path('archives/<int:id>', archives, name='archives'),
    path('penulis/<str:user>', Penulis.as_view(), name='penulis'),
    path('profile/', TemplateView.as_view(template_name='blog/profile.html'), name='profile'),
    path('<kategori>/', PostListView.as_view(), name='kategori'),
]

project/risset/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_view
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from .views import home
# from .admin import admin_site

admin.autodiscover()

urlpatterns = [
    path('', home, name='home'),
    path('home/', TemplateView.as_view(template_name='index.html'), name='home'),
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('password-reset/', auth_view.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_view.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_view.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('dashboard/', TemplateView.as_view(template_name='users/dashboard.html'), name='dashboard'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('podcast/', include('podcast.urls', namespace='podcast')),
    path('users/', include('users.urls', namespace='users')),
    path('video/', include('video.urls', namespace='video')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import register, activate, Profile, Bookmarks,  Follow, tambah_artikel, update_artikel, delete_artikel
app_name="users"

urlpatterns = [
    path('', Profile, name='profile'),
    path('follow/<user_id>', Follow.as_view(), name='follow'),
    path('tambah-artikel/', tambah_artikel, name="tambah-artikel"),
    path('update-artikel/<int:id>', update_artikel, name="update-artikel"),
    path('delete-artikel/<int:id>', delete_artikel, name="delete-artikel"),
    path('register/', register, name='register'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('bookmark/', Bookmarks.as_view(), name='bookmark'),
]

project/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to='user/profile', default='default.jpg', blank=True, null=True)
    alamat = models.CharField(max_length=250, blank=True, null=True)
    status = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.foto.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.foto.path)


class UserFollowing(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following", blank=True)
    following_user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name="followers", blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("user_id", "following_user_id")
        ordering = ["-created"]

    def __str__(self):
        return "{} follow {}".format(self.following_user_id,self.user_id)

project/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, UserFollowing
from blog.models import Post
from ckeditor_uploader.fields import RichTextUploadingField


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    
class ProfileUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ['foto', 'alamat', 'status']


# class UserFollowingForm(forms.ModelForm):
    
#     class Meta:
#         model = UserFollowing
#         fields = ("user_id", "following_user_id", "created",)


class PostForm(forms.ModelForm):
    # judul = forms.CharField(required=False)
    # thumbnail = forms.ImageField(required=False)
    # atrikel = forms.CharField(widget=RichTextUploadingField(config_name="special"))
    class Meta:
        model = Post
        fields = ('judul','thumbnail', 'atrikel',)
        widgets = {
            'atrikel':  forms.CharField(widget=RichTextUploadingField(config_name="special"))
        }

project/users/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.utils.encoding import force_text
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.core.mail import EmailMessage
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View

from .tokens import account_activation_token
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm, PostForm


from .models import Profile, UserFollowing
from blog.models import Post
# Create your views here.


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('users/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':force_text(urlsafe_base64_encode(force_bytes(user.pk))),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'users/email_konfirmasi_daftar.html')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, user.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return render(request, 'users/email_konfirmasi_daftar_done.html')
    else:
        return render (request, 'users/email_konfirmasi_invalid.html')


@login_required
def Profile(request):
    users = request.user
    posts = users.posts.filter(publish=True)
    likes = users.requirement_post_likes.all()
    archives = users.archives.all()
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Anda berhasil mengubah akun')
            # return redirect('users:profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'users': request.user,
        'posts': posts,
        'likes': likes,
        'archives': archives,
    }
    return render(request, 'users/profile.html', context)


class Bookmarks(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'next'
    template_name = 'users/bookmark.html'

    def get(self, request, *args, **kwargs):
        users = request.user
        likes = users.requirement_post_likes.all()
        bookmarks = users.bookmarks.all()
        archives = users.archives.all()
        print(archives)
        
        self.context = {
            'likes':likes,
            'users':users,
            'bookmarks':bookmarks,
            'archives': archives
        }
        return render(self.request, self.template_name, self.context)


class Follow(LoginRequiredMixin, View):
    login_url = "/login/"
    redirect_field_name ="next"

    def get(self, request, *args, **kwargs):
        user = User.objects.get(id=self.kwargs['user_id'])
        follow = request.user
        a = UserFollowing.objects.values_list('user_id', flat=True).distinct()
        for b in a:
            print(b)
            print(follow.id, " = ", follow)
        # UserFollowing.objects.create(user_id=user,following_user_id=follow)

        # try:
        #     user.following
        # except User.following.RelatedObjectDoesNotExist as identifier:
        #     UserFollowing.objects.create(user_id=user)
        if user.id != follow.id:
            print(user, follow.id)
            if follow.id in a:
                UserFollowing.objects.filter(user_id=user,following_user_id=follow).delete()
            else:
                UserFollowing.objects.create(user_id=user,following_user_id=follow)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            messages.error(self.request, "maaf, anda tidak bisa mengikuti dri anda sendiri")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))    
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        

@login_required
def tambah_artikel(request):
    # posts = Post.objects.filter(active=True).order_by('-created')
    # common_tags = Post.tags.most_common()[:4]
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.slug = slugify(newpost.judul)
            newpost.user = request.user
            newpost.save()

            # form.save_m2m()
            messages.success(
                request, 'Anda berhasil menambahkan artikel'
            )
            return redirect('users:profile')
    else:
        form = PostForm()
    
    context = {
        'form': form,
    }
    return render(request, 'users/tambah_artikel.html', context)


@login_required
def update_artikel(request, id=None):
    post = get_object_or_404(Post, id=id)
    penulis = post.user.username
    if request.method == 'POST' and request.user.is_authenticated and request.user.username:
        form = PostForm(request.POST or None, request.FILES or None, instance=post)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.slug = slugify(newpost.judul)
            newpost.save()

            messages.success(
                request, 'Anda berhasil mengubah artikel'
            )
            return redirect('users:profile')
    else:
        form = PostForm(request.POST or None, request.FILES or None, instance=post)
    
    context = {
        'post': post,
        'form': form,
        'penulis': penulis
    }
    return render(request, 'users/edit_artikel.html', context)


@login_required
def delete_artikel(request, id=None):
    post = get_object_or_404(Post, id=id)
    users = post.user.username
    if request.method == 'POST' and request.user.is_authenticated and request.user.username:
        post.delete()
        messages.success(request, "Artikel berhasil dihapus!")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    
    context = {
        'post': post,
        'users': users
    }
    
    return render(request, 'users/delete_konfirmasi.html', context)

project/users/templates/users/acc_active_email.html
{% autoescape off %}
=======> Konfirmasi email <=======
Hi {{ user.username }},
Silahkan periksa tautan untuk mengkonfirmasi pendaftaran,
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

project/users/templates/users/delete_artikel.html
{% load crispy_forms_tags %}
<div id="DangerModalalert" class="modal modal-adminpro-general default-popup-DangerModal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-close-area modal-close-df">
                <a class="close" data-dismiss="modal" href="#"><i class="fa fa-close"></i></a>
            </div>
            
                <div class="modal-body">
                    {% comment %} <i class="fa fa-check modal-check-pro"></i> {% endcomment %}
                    <h2>Delete Artikel</h2>
                    <p>Anda yakin ingin menghapus postingan <br><b>{{post.judul}}</b></p>
                </div>
                <div class="modal-footer">
                <form action="{% url 'users:delete-artikel' post.id %}" method="POST">
                    {% csrf_token %}
                    <button data-dismiss="modal" class="btn btn-default">Tidak</button>
                    <button  type="submit" id="basicSuccessNoDelay" class="btn btn-danger">Hapus</button>
                </form>
                </div>
        </div>
    </div>
</div>

project/users/templates/users/edit_artikel.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/styles/post.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/styles/post_responsive.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/shadow.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/post-meta.css' %}">
{% endblock extra_head %}

{% block header %}
<div class="home">
	<div class="home_background parallax-window" data-parallax="scroll" data-image-src="{% static 'blog/images/post.jpg' %}" data-speed="0.1"></div>
</div>
{% endblock header %}

{% block contents %}
  <div class="col-md-10 offset-md-1 mb-5">
    <div class="post_content">
        <div class="mt-5">
        <h1 class="text-center">Update Artikel</h1>


        <div class="post_body s_dow">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <input type="submit" value="save" class="btn btn-outline-secondary btn-lg btn-block">
          </form>
		    </div>
    </div>
  </div>
{% endblock contents %}

{% block extra_body %}
<script src="{% static 'blog/js/post.js' %}"></script>
{% endblock extra_body %}

project/users/templates/users/email_konfirmasi_daftar.html
{% extends 'users/base.html' %}

{% block contents %}
<div class="col-lg-6">
    <div class="login-bg">
        <div class="row">
            <div class="col-lg-12">
                <div class="login-title">
                    <div class="alert alert-warning alert-mg-b">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Periksa email anda!</strong> Harap konfirmasi alamat email anda untuk menyelesaikan pendaftaran.
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contents %}

project/users/templates/users/email_konfirmasi_daftar_done.html
{% extends 'users/base.html' %}

{% block contents %}
<div class="col-lg-6">
    <div class="login-bg">
        <div class="row">
            <div class="col-lg-12">
                <div class="login-title">
                    <div class="alert alert-success alert-mg-b">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Terima kasih atas konfirmasi email!</strong> Sekarang anda dapat <a href="{% url 'login' %}">masuk </a> akun anda.
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contents %}

project/users/templates/users/email_konfirmasi_invalid.html
{% extends 'users/base.html' %}

{% block contents %}
<div class="col-lg-6">
    <div class="login-bg">
        <div class="row">
            <div class="col-lg-12">
                <div class="login-title">
                    <div class="alert alert-danger alert-mg-b">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Tautan aktivasi tidak valid!</strong>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contents %}

project/users/templates/users/login.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block contents %}
<form id="adminpro-form" class="adminpro-form" method="POST" action="{% url 'login' %}">
    {% csrf_token %}
    <div class="col-lg-6">
        <div class="login-bg">
            <div class="row">
                <div class="col-lg-12">
                    <div class="login-title">
                        <h1 class="text-center">Selamat Datang!</h1>
                    </div>
                </div>
            </div>
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-success alert-mg-b">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <strong>Berhasil!</strong> {{message}}
                </div>
                {% endfor %}
            {% endif %}
            {% if form.errors %}
            <div class="alert alert-danger alert-mg-b">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>Password dan username tidak cocok.</strong> Coba login kembali.
            </div>
            {% endif %}
            {% if next %}
                {% if user.is_authenticated %}
                <div class="alert alert-danger alert-mg-b">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <strong>Gagal!</strong> Akun anda tidak memiliki akses ke halaman ini. To proceed,
                please login with an account that has access.
                </div>
                {% else %}
                <div class="alert alert-danger alert-mg-b">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <strong>Gagal!</strong> Tolong login dengan pada halaman ini.
                </div>
                {% endif %}
            {% endif %}
            <div class="row">
                <div class="col-lg-4">
                    <div class="login-input-head">
                        <p>{{ form.username.label_tag }}</p>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="login-input-area">
                        {{ form.username }}
                        <i class="fa fa-envelope login-user" aria-hidden="true"></i>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="login-input-head">
                        <p>{{ form.password.label_tag }}</p>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="login-input-area">
                        {{ form.password }}
                        <i class="fa fa-lock login-user"></i>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="forgot-password">
                                <a href="{% url 'password_reset' %}">Lupa password?</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">

                </div>
                <div class="col-lg-8">
                    <div class="login-button-pro">
                        <a href="{% url 'users:register' %}" class="login-button login-button-rg">Register</a>
                        <button type="submit" class="login-button login-button-lg">Log in</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock contents %}

project/users/templates/users/modals.html
<div id="PrimaryModalhdbgcl" class="modal modal-adminpro-general default-popup-PrimaryModal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header header-color-modal bg-color-1">
                <h4 class="modal-title">BG Color Header Modal</h4>
                <div class="modal-close-area modal-close-df">
                    <a class="close" data-dismiss="modal" href="#"><i class="fa fa-close"></i></a>
                </div>
            </div>
            <div class="modal-body">
                <i class="fa fa-check modal-check-pro"></i>
                <h2>Awesome!</h2>
                <p>The Modal plugin is a dialog box/popup window that is displayed on top of the current page</p>
            </div>
            <div class="modal-footer">
                <a data-dismiss="modal" href="#">Cancel</a>
                <a href="#">Process</a>
            </div>
        </div>
    </div>
</div>

project/users/templates/users/password_reset.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block contents %}
<form id="adminpro-form" class="adminpro-form" method="POST">
    {% csrf_token %}
    <div class="col-lg-6">
        <div class="login-bg">
            <div class="row">
                <div class="col-lg-12">
                    <div class="login-title">
                        <h1 class="text-center">Masukan email aktif anda!</h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    {{form|crispy}}
                </div>
            </div>

            <div class="row">
                <div class="col-lg-5">

                </div>
                <div class="col-lg-7">
                    <div class="login-button-pro">
                        <button type="submit" class="login-button login-button-lg">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock contents %}

project/users/templates/users/password_reset_done.html
{% extends 'users/base.html' %}

{% block contents %}
<div class="col-lg-6">
    <div class="login-bg">
        <div class="row">
            <div class="col-lg-12">
                <div class="login-title">
                    <div class="alert alert-success alert-mg-b">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Periksa email anda!</strong> Untuk melanjutkan intruksi reset password.
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contents %}

project/users/templates/users/register.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block contents %}
<form id="adminpro-register-form" class="adminpro-form" method="POST">
    {% csrf_token %}
    <div class="col-lg-6">
        <div class="login-bg">
            <div class="row">
                <div class="col-lg-12">
                    <div class="login-title">
                        <h1 class="text-center">Daftar Sekarang!</h1>
                    </div>
                </div>
            </div>
            {% if form.errors %}
                    <div class="alert alert-danger alert-mg-b">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Coba Lagi!</strong> pengisian formulir tidak sesuai prosedur.
                    </div>
            {% endif %}
            <div class="row">
                <div class="col-lg-4">
                    <div class="login-input-head">
                        <p>{{form.username.label_tag}}</p>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="login-input-area">
                        {{form.username}}
                        <i class="fa fa-user login-user"></i>
                         <small id="hint_id_username" class="form-text text-muted">Wajib. 150 karakter atau kurang. Hanya huruf, angka dan @/./+/-/_.</small> 
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="login-input-head">
                        <p>{{form.email.label_tag}}</p>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="login-input-area">
                        {{form.email}}
                        <i class="fa fa-envelope login-user" aria-hidden="true"></i>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="login-input-head">
                        <p>{{form.password1.label_tag}}</p>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="login-input-area">
                        {{form.password1}}
                        <i class="fa fa-lock login-user"></i>
                        <small id="hint_id_password1" class="form-text text-muted">
                            <ul>
                                <li>Kata sandi tidak boleh terlalu mirip dengan informasi pribadi anda yang lain.</li>
                                <li>Kata sandi harus mengandung setidaknya 8 karakter.</li><li>Kata sandi tidak dapat menjadi kata sandi yang umum digunakan.<li>
                                <li>Kata sandi tidak bisa terdiri dari angka semua.</li>
                            </ul>
                        </small>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="login-input-head">
                        <p>{{form.password2.label_tag}}</p>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="login-input-area">
                        {{form.password2}}
                        <i class="fa fa-lock login-user"></i>
                        <small id="hint_id_password2" class="form-text text-muted">Masukan kata sandi sama seperti sebelumnya, untuk verifikasi.</small>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4"></div>
                <div class="col-lg-8">
                    <div class="login-button-pro">
                        <a href="{% url 'login' %}" class="login-button login-button-rg">Log In</a>
                        <button type="submit" class="login-button login-button-lg">Register</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock contents %}

project/users/templates/users/update.html
{% load crispy_forms_tags %}
<div id="PrimaryModalalert" class="modal modal-adminpro-general default-popup-PrimaryModal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-close-area modal-close-df">
                <a class="close" data-dismiss="modal" href="#"><i class="fa fa-close"></i></a>
            </div>
            <form method="post" enctype="multipart/form-data">
                <div class="modal-body">
                    {% comment %} <i class="fa fa-check modal-check-pro"></i> {% endcomment %}
                    {% csrf_token %}
                    <h2>Update Profile</h2>
                    {{u_form|crispy}}
                    {{p_form|crispy}}
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">Kembali</button>
                    <button  type="submit" id="basicSuccessNoDelay" class="btn btn-success">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>