project/blog/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import PostListView, PostDetailView, LikeDislike, Comment, bookmarks, Penulis, archives, AllPost, Tags, search

app_name = "blog"

urlpatterns = [
    path('', AllPost.as_view(), name='home'),
    path('videos/', TemplateView.as_view(template_name='blog/videos.html'), name='videos'),
    path('post/<slug>/', PostDetailView.as_view(), name='detail'),
    path('tags/<str:tag>', Tags.as_view(), name='tag'),
    path('search/',search, name='search' ),
    path('requirement/<int:post_id>/<str:opinion>', LikeDislike.as_view(), name='like_dislike'),
    path('comment/<str:slug>', Comment.as_view(), name='comment'),
    path('video-detail/', TemplateView.as_view(template_name='blog/single-video.html'), name='video-detail'),
    path('bookmarks/<int:id>', bookmarks, name='bookmarks'),
    path('archives/<int:id>', archives, name='archives'),
    path('penulis/<str:user>', Penulis.as_view(), name='penulis'),
    path('profile/', TemplateView.as_view(template_name='blog/profile.html'), name='profile'),
    path('<kategori>/', PostListView.as_view(), name='kategori'),
]

project/risset/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_view
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from .views import home
# from .admin import admin_site

admin.autodiscover()

urlpatterns = [
    path('', home, name='home'),
    path('home/', TemplateView.as_view(template_name='index.html'), name='home'),
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('password-reset/', auth_view.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_view.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_view.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('dashboard/', TemplateView.as_view(template_name='users/dashboard.html'), name='dashboard'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('podcast/', include('podcast.urls', namespace='podcast')),
    path('users/', include('users.urls', namespace='users')),
    path('video/', include('video.urls', namespace='video')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import register, activate, Profile, Bookmarks,  Follow, tambah_artikel, update_artikel, delete_artikel
app_name="users"

urlpatterns = [
    path('', Profile, name='profile'),
    path('follow/<user_id>', Follow.as_view(), name='follow'),
    path('tambah-artikel/', tambah_artikel, name="tambah-artikel"),
    path('update-artikel/<int:id>', update_artikel, name="update-artikel"),
    path('delete-artikel/<int:id>', delete_artikel, name="delete-artikel"),
    path('register/', register, name='register'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('bookmark/', Bookmarks.as_view(), name='bookmark'),
]

project/templates/snippets/admin-scripts.html
{% load static %}
<!-- jquery
    ============================================ -->
<script src="{% static 'admin/js/vendor/jquery-1.11.3.min.js' %}"></script>
<!-- bootstrap JS
    ============================================ -->
<script src="{% static 'admin/js/bootstrap.min.js' %}"></script>
<!-- meanmenu JS
    ============================================ -->
<script src="{% static 'admin/js/jquery.meanmenu.js' %}"></script>
<!-- mCustomScrollbar JS
    ============================================ -->
<script src="{% static 'admin/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<!-- sticky JS
    ============================================ -->
<script src="{% static 'admin/js/jquery.sticky.js' %}"></script>
<!-- scrollUp JS
    ============================================ -->
<script src="{% static 'admin/js/jquery.scrollUp.min.js' %}"></script>
<!-- counterup JS
    ============================================ -->
<script src="{% static 'admin/js/counterup/jquery.counterup.min.js' %}"></script>
<script src="{% static 'admin/js/counterup/waypoints.min.js' %}"></script>
<script src="{% static 'admin/js/counterup/counterup-active.js' %}"></script>
<!-- peity JS
    ============================================ -->
<script src="{% static 'admin/js/peity/jquery.peity.min.js' %}"></script>
<script src="{% static 'admin/js/peity/peity-active.js' %}"></script>
<!-- sparkline JS
    ============================================ -->
<script src="{% static 'admin/js/sparkline/jquery.sparkline.min.js' %}"></script>
<script src="{% static 'admin/js/sparkline/sparkline-active.js' %}"></script>
<!-- flot JS
    ============================================ -->
{% comment %} <script src="{% static 'admin/js/flot/jquery.flot.js' %}"></script>
<script src="{% static 'admin/js/flot/jquery.flot.tooltip.min.js' %}"></script>
<script src="{% static 'admin/js/flot/jquery.flot.spline.js' %}"></script>
<script src="{% static 'admin/js/flot/jquery.flot.resize.js' %}"></script>
<script src="{% static 'admin/js/flot/jquery.flot.pie.js' %}"></script>
<script src="{% static 'admin/js/flot/Chart.min.js' %}"></script>
<script src="{% static 'admin/js/flot/flot-active.js' %}"></script> {% endcomment %}
<!-- map JS
    ============================================ -->
<script src="{% static 'admin/js/map/raphael.min.js' %}"></script>
<script src="{% static 'admin/js/map/jquery.mapael.js' %}"></script>
<script src="{% static 'admin/js/map/france_departments.js' %}"></script>
<script src="{% static 'admin/js/map/world_countries.js' %}"></script>
<script src="{% static 'admin/js/map/usa_states.js' %}"></script>
<script src="{% static 'admin/js/map/map-active.js' %}"></script>
<!-- data table JS
    ============================================ -->
<script src="{% static 'admin/js/data-table/bootstrap-table.js' %}"></script>
<script src="{% static 'admin/js/data-table/tableExport.js' %}"></script>
<script src="{% static 'admin/js/data-table/data-table-active.js' %}"></script>
<script src="{% static 'admin/js/data-table/bootstrap-table-editable.js' %}"></script>
<script src="{% static 'admin/js/data-table/bootstrap-editable.js' %}"></script>
<script src="{% static 'admin/js/data-table/bootstrap-table-resizable.js' %}"></script>
<script src="{% static 'admin/js/data-table/colResizable-1.5.source.js' %}"></script>
<script src="{% static 'admin/js/data-table/bootstrap-table-export.js' %}"></script>


<script src="{% static 'admin/js/dropzone.js' %}"></script>
<!-- main JS
    ============================================ -->
<script src="{% static 'admin/js/main.js' %}"></script>

project/templates/snippets/admin-styles.html
{% load static %}
<link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico">
<!-- Google Fonts
    ============================================ -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i,800" rel="stylesheet">
<!-- Bootstrap CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'admin/css/bootstrap.min.css' %}">
<!-- Bootstrap CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'admin/css/font-awesome.min.css' %}">
<!-- adminpro icon CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'admin/css/adminpro-custon-icon.css' %}">
<!-- meanmenu icon CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'admin/css/meanmenu.min.css' %}">
<!-- mCustomScrollbar CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'admin/css/jquery.mCustomScrollbar.min.css' %}">
<!-- animate CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'admin/css/animate.css' %}">
<!-- data-table CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'admin/css/data-table/bootstrap-table.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/data-table/bootstrap-editable.css' %}">
<!-- normalize CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'admin/css/normalize.css' %}">
<!-- charts C3 CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'admin/css/c3.min.css' %}">
<!-- forms CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'admin/css/form/all-type-forms.css' %}">
<!-- style CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'admin/style.css' %}">
<!-- responsive CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'admin/css/responsive.css' %}">
<!-- modernizr JS
    ============================================ -->
<script src="{% static 'admin/js/vendor/modernizr-2.8.3.min.js' %}"></script>

project/templates/snippets/footer.html
{% load static %}
<footer class="footer">
    <div class="container">
        <div class="row row-lg-eq-height">
            <div class="col-lg-9 order-lg-1 order-2">
                <div class="footer_content">
                    <div class="footer_logo"><a href="#">Risset</a></div>
                    <div class="footer_social">
                        <ul>
                            <li class="footer_social_facebook"><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li class="footer_social_twitter"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                            <li class="footer_social_pinterest"><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                            <li class="footer_social_vimeo"><a href="#"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
                            <li class="footer_social_instagram"><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                            <li class="footer_social_google"><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                    <div class="copyright">
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="" target="_blank">Risset</a>
</div>
                </div>
            </div>
            <div class="col-lg-3 order-lg-2 order-1">
                <div class="subscribe">
                    <div class="subscribe_background"></div>
                    <div class="subscribe_content">
                        <div class="subscribe_title">Subscribe</div>
                        <form action="#">
                            <input type="email" class="sub_input" placeholder="Your Email" required="required">
                            <button class="sub_button">
                                <svg version="1.1" id="link_arrow_1" x="0px" y="0px"
                                        width="19px" height="13px" viewBox="0 0 19 13" enable-background="new 0 0 19 13" xml:space="preserve">
                                {% comment %} <svg version="1.1" id="link_arrow_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                        width="19px" height="13px" viewBox="0 0 19 13" enable-background="new 0 0 19 13" xml:space="preserve"> {% endcomment %}
                                    <polygon fill="#FFFFFF" points="12.475,0 11.061,0 17.081,6.021 0,6.021 0,7.021 17.038,7.021 11.06,13 12.474,13 18.974,6.5 "/>
                                </svg>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

project/templates/snippets/navbar.html
{% load static %}
<!-- Header -->
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="header_content d-flex flex-row align-items-center justify-content-start">
                    <div class="logo"><a href="{% url 'home' %}">Risset</a></div>
                    <nav class="main_nav">
                        <ul>
                            <li class="active"><a href="{% url 'home' %}">Home</a></li>
                            <li><a href="{% url 'blog:home' %}">Blog</a></li>
                            <li><a href="{% url 'podcast:home' %}">Podcast</a></li>
                            <li><a href="{% url 'video:home' %}">Video</a></li>
                            <li><a href="#">About</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </nav>
                    <div class="search_container ml-auto">
                        <div class="weather">
                            <div class="temperature"><a href="{% url 'users:bookmark' %}"><i class="fa fa-bookmark" aria-hidden="true" style="font-size: 25px;"></i></a></div>
                        </div>
                        <form action="{% url 'blog:search' %}" method="GET", value="{{request.GET.q}}">
                            <input type="text" name="q" value="{{request.GET.q}}" class="header_search_input" required="required" placeholder="Pencarian...">
                            <input type="hidden" value="Search" name="submit"><img class="header_search_icon" src="{% static 'blog/images/search.png' %}" alt="">
                        </form> 
                        {% comment %} <form action="{% url 'search:searchposts' %}" method="GET" value="{{request.GET.q}}">
                        Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search posts"/>
                        <input type="submit" name="submit" value="Search"/>
                        </form> {% endcomment %}
                    </div>
                    {% if user.is_authenticated %}
                    <div class="main_nav ml-auto">
                        <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link ">
                            <div class="comment_author_image"><div><img src="{{user.profile.foto.url}}" alt="" style=" border: 2px solid white; width: 35px; height: 35px; border-radius: 50%"></div></div>
                        </a>
                        <nav class="menu_nav">
                            <ul role="menu_nav navbar-nav" class="dropdown-header-top dropdown-menu animated flipInX mt-5 menu_mm pl-2">
                                <li class="nav-item menu_mm"><a href="{% url 'users:profile' %}">My Profile</a>
                                </li>
                                <li class="nav-item menu_mm"><a href="{% url 'users:bookmark' %}">Bookmark</a>
                                </li>
                                <li class="nav-item menu_mm"><a href="#">Settings</a>
                                </li>
                                <li class="nav-item menu_mm">
                                <a class="Warning Warning-color mg-b-10" href="#" data-toggle="modal" data-target="#WarningModalalert"><span class="adminpro-icon adminpro-locked author-log-ic"></span>Logout</a>
                                </li>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    {% else %}
                    <nav class="main_nav">
                        <ul>
                            <li><a href="{% url 'users:register' %}">Register</a></li>
                            <li><a href="{% url 'login' %}">Login</a></li>
                        </ul>   
                    </nav> 
                    {% endif %}
                    <div class="hamburger ml-auto menu_mm">
                        <i class="fa fa-bars trans_200 menu_mm" aria-hidden="true"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Menu -->

<div class="menu d-flex flex-column align-items-end justify-content-start text-right menu_mm trans_400">
    <div class="menu_close_container"><div class="menu_close"><div></div><div></div></div></div>
    <div class="logo menu_mm"><a href="{% url 'home' %}">Risset</a></div>
    <div class="search">
        <form action="{% url 'blog:search' %}" method="GET", value="{{request.GET.q}}">
            <input type="text" type="text" name="q" value="{{request.GET.q}}"  class="header_search_input menu_mm" required="required" placeholder="Pencarian...">
            <input type="hidden" value="Search" name="submit"><img class="header_search_icon menu_mm" src="{% static 'blog/images/search_2.png' %}" alt="">
        </form>
    </div>
    <nav class="menu_nav">
        <ul class="menu_mm">
            <li class="menu_mm"><a href="index.html">home</a></li>
            <hr>
            {% if user.is_authenticated %}
            <li class="nav-item menu_mm"><a href="{% url 'users:profile' %}">My Profile</a>
            </li>
            <li class="nav-item menu_mm"><a href="{% url 'users:bookmark' %}">Bookmark</a>
            </li>
            <li class="nav-item menu_mm"><a href="#">Settings</a>
            </li>
            <li class="nav-item menu_mm"><a class="Warning Warning-color mg-b-10" href="#" data-toggle="modal" data-target="#WarningModalalert"><span class="adminpro-icon adminpro-locked author-log-ic"></span>Logout</a>
            </li>
            {% else %}
            <li class="nav-item menu_mm"><a href="{% url 'users:register' %}">Register</a>
            <li class="nav-item menu_mm"><a href="{% url 'login' %}">Login</a>
            {% endif %}
            {% comment %} <li class="menu_mm"><a class="Warning Warning-color mg-b-10" href="#" data-toggle="modal" data-target="#WarningModalalert">Logout</a> {% endcomment %}
            </li>
            <hr>
            <li class="menu_mm"><a href="#">Blog</a></li>
            <li class="menu_mm"><a href="{% url 'podcast:home' %}">Podcast</a></li>
            <li class="menu_mm"><a href="{% url 'video:home' %}">Video</a></li>
            <li class="menu_mm"><a href="#">Contact</a></li>
        </ul>
    </nav>
</div>

project/templates/snippets/scripts.html
{% load static %}
<script src="{% static 'blog/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'blog/styles/bootstrap4/popper.min.js' %}"></script>
<script src="{% static 'blog/styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'blog/plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'blog/plugins/easing/easing.js' %}"></script>
<script src="{% static 'blog/plugins/masonry/masonry.js' %}"></script>
<script src="{% static 'blog/plugins/masonry/images_loaded.js' %}"></script>
<script src="{% static 'blog/plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'blog/js/custom.js' %}"></script>

project/templates/snippets/styles.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/styles/bootstrap4/bootstrap.min.css' %}">
<link href="{% static 'blog/plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'blog/plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/plugins/OwlCarousel2-2.2.1/animate.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'blog/styles/main_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/styles/responsive.css' %}">

project/templates/snippets/users_scripts.html
{% load static %}
<!-- jquery
    ============================================ -->
<script src="{% static 'users/js/vendor/jquery-1.11.3.min.js' %}"></script>
<!-- bootstrap JS
    ============================================ -->
<script src="{% static 'users/js/bootstrap.min.js' %}"></script>
<!-- meanmenu JS
    ============================================ -->
<script src="{% static 'users/js/jquery.meanmenu.js' %}"></script>
<!-- mCustomScrollbar JS
    ============================================ -->
<script src="{% static 'users/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<!-- sticky JS
    ============================================ -->
<script src="{% static 'users/js/jquery.sticky.js' %}"></script>
<!-- scrollUp JS
    ============================================ -->
<script src="{% static 'users/js/jquery.scrollUp.min.js' %}"></script>
<!-- counterup JS
    ============================================ -->
<script src="{% static 'users/js/counterup/jquery.counterup.min.js' %}"></script>
<script src="{% static 'users/js/counterup/waypoints.min.js' %}"></script>
<script src="{% static 'users/js/counterup/counterup-active.js' %}"></script>
<!-- peity JS
    ============================================ -->
<script src="{% static 'users/js/peity/jquery.peity.min.js' %}"></script>
<script src="{% static 'users/js/peity/peity-active.js' %}"></script>
<!-- sparkline JS
    ============================================ -->
<script src="{% static 'users/js/sparkline/jquery.sparkline.min.js' %}"></script>
<script src="{% static 'users/js/sparkline/sparkline-active.js' %}"></script>
<!-- flot JS
    ============================================ -->
<script src="{% static 'users/js/flot/jquery.flot.js' %}"></script>
<script src="{% static 'users/js/flot/jquery.flot.tooltip.min.js' %}"></script>
<script src="{% static 'users/js/flot/jquery.flot.spline.js' %}"></script>
<script src="{% static 'users/js/flot/jquery.flot.resize.js' %}"></script>
<script src="{% static 'users/js/flot/jquery.flot.pie.js' %}"></script>
<script src="{% static 'users/js/flot/Chart.min.js' %}"></script>
<script src="{% static 'users/js/flot/flot-active.js' %}"></script>
<!-- map JS
    ============================================ -->
<script src="{% static 'users/js/map/raphael.min.js' %}"></script>
<script src="{% static 'users/js/map/jquery.mapael.js' %}"></script>
<script src="{% static 'users/js/map/france_departments.js' %}"></script>
<script src="{% static 'users/js/map/world_countries.js' %}"></script>
<script src="{% static 'users/js/map/usa_states.js' %}"></script>
<script src="{% static 'users/js/map/map-active.js' %}"></script>
<!-- data table JS
    ============================================ -->
<script src="{% static 'users/js/data-table/bootstrap-table.js' %}"></script>
<script src="{% static 'users/js/data-table/tableExport.js' %}"></script>
<script src="{% static 'users/js/data-table/data-table-active.js' %}"></script>
<script src="{% static 'users/js/data-table/bootstrap-table-editable.js' %}"></script>
<script src="{% static 'users/js/data-table/bootstrap-editable.js' %}"></script>
<script src="{% static 'users/js/data-table/bootstrap-table-resizable.js' %}"></script>
<script src="{% static 'users/js/data-table/colResizable-1.5.source.js' %}"></script>
<script src="{% static 'users/js/data-table/bootstrap-table-export.js' %}"></script>
<!-- main JS
    ============================================ -->
<script src="{% static 'blog/plugins/jquery.mb.YTPlayer-3.1.12/jquery.mb.YTPlayer.js' %}"></script>
<script src="{% static 'blog/plugins/easing/easing.js' %}"></script>
<script src="{% static 'blog/plugins/masonry/masonry.js' %}"></script>
<script src="{% static 'blog/plugins/masonry/images_loaded.js' %}"></script>
<script src="{% static 'blog/plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'blog/js/custom.js' %}"></script>

<script src="{% static 'users/js/modal-active.js' %}"></script>
<script src="{% static 'users/js/main.js' %}"></script>

project/templates/snippets/users_styles.html
{% load static %}

<link rel="shortcut icon" type="users/image/x-icon" href="{% static 'img/favicon.ico' %}">
<!-- Google Fonts
    ============================================ -->
{% comment %} <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i,800" rel="stylesheet"> {% endcomment %}
<!-- Bootstrap CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'users/css/bootstrap.min.css' %}">
<!-- Bootstrap CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'users/css/font-awesome.min.css' %}">
<!-- adminpro icon CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'users/css/adminpro-custon-icon.css' %}"> 
<!-- meanmenu icon CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'users/css/meanmenu.min.css' %}">

{% comment %} <!-- data-table CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'users/css/data-table/bootstrap-table.css' %}">
<link rel="stylesheet" href="{% static 'users/css/data-table/bootstrap-editable.css' %}"> {% endcomment %}
<!-- mCustomScrollbar CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'users/css/jquery.mCustomScrollbar.min.css' %}">
<!-- modals CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'users/css/modals.css' %}">
<!-- tabs CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'users/css/tabs.css' %}">
<!-- animate CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'users/css/animate.css' %}">
<!-- normalize CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'users/css/normalize.css' %}">
<!-- form CSS
    ============================================ -->
{% comment %} <link rel="stylesheet" href="{% static 'users/css/form/all-type-forms.css' %}">
<link rel="stylesheet" href="{% static 'users/css/form.css' %}"> {% endcomment %}
<!-- style CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'users/style.css' %}">
<!-- responsive CSS
    ============================================ -->
<link rel="stylesheet" href="{% static 'users/css/responsive.css' %}">

<!-- modernizr JS
    ============================================ -->
<script src="{% static 'users/js/vendor/modernizr-2.8.3.min.js' %}"></script>