project/blog/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import PostListView, PostDetailView, LikeDislike, Comment, bookmarks, Penulis, archives, AllPost, Tags, search

app_name = "blog"

urlpatterns = [
    path('', AllPost.as_view(), name='home'),
    path('videos/', TemplateView.as_view(template_name='blog/videos.html'), name='videos'),
    path('post/<slug>/', PostDetailView.as_view(), name='detail'),
    path('tags/<str:tag>', Tags.as_view(), name='tag'),
    path('search/',search, name='search' ),
    path('requirement/<int:post_id>/<str:opinion>', LikeDislike.as_view(), name='like_dislike'),
    path('comment/<str:slug>', Comment.as_view(), name='comment'),
    path('video-detail/', TemplateView.as_view(template_name='blog/single-video.html'), name='video-detail'),
    path('bookmarks/<int:id>', bookmarks, name='bookmarks'),
    path('archives/<int:id>', archives, name='archives'),
    path('penulis/<str:user>', Penulis.as_view(), name='penulis'),
    path('profile/', TemplateView.as_view(template_name='blog/profile.html'), name='profile'),
    path('<kategori>/', PostListView.as_view(), name='kategori'),
]

project/podcast/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import AllPodcast, PodcastListView, TagsPodcast, PodcastDetailView, PodcastComment, PodcastLikeDislike, PenulisPodcast, podcast_bookmarks, podcast_archives

app_name = "podcast"

urlpatterns = [
    path('', AllPodcast.as_view(), name='home'),
    path('<str:kategori>/', PodcastListView.as_view(), name='kategori'),
    path('post/<str:slug>/', PodcastDetailView.as_view(), name='detail'),
    path('comment/<str:slug>', PodcastComment.as_view(), name='comment'),
    path('requirement/<int:podcast_id>/<str:opinion>', PodcastLikeDislike.as_view(), name='like_dislike'),
    path('tag/<str:tag>/', TagsPodcast.as_view(), name='tag'),
    path('detail/', TemplateView.as_view(template_name='podcast/single-podcast.html'), name='detail'),
    path('bookmarks/<int:id>', podcast_bookmarks, name='bookmarks'),
    path('archives/<int:id>', podcast_archives, name='archives'),
    path('penulis/<str:user>/', PenulisPodcast.as_view(), name='penulis'),
]

project/risset/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_view
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from .views import home
# from .admin import admin_site

admin.autodiscover()

urlpatterns = [
    path('', home, name='home'),
    path('home/', TemplateView.as_view(template_name='index.html'), name='home'),
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('password-reset/', auth_view.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_view.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_view.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('dashboard/', TemplateView.as_view(template_name='users/dashboard.html'), name='dashboard'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('podcast/', include('podcast.urls', namespace='podcast')),
    path('users/', include('users.urls', namespace='users')),
    path('video/', include('video.urls', namespace='video')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse
from django.conf import settings
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.

class Kategori(models.Model):
    kategori = models.CharField(max_length=125)

    def __str__(self):
        return self.kategori


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    judul = models.CharField(max_length=125)
    thumbnail = models.ImageField(upload_to='blog/post')
    kategori = models.ForeignKey(Kategori, on_delete=models.CASCADE, blank=True, null=True, related_name='kategoris')
    tags = TaggableManager(blank=True)
    atrikel = RichTextUploadingField(blank=True, null=True, config_name='default')
    views = models.PositiveIntegerField(default=0)
    bookmarks = models.ManyToManyField(User, related_name='bookmarks', blank=True)
    archive = models.ManyToManyField(User, related_name="archives", blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    publish = models.BooleanField(default=False, editable=False)
    slug = models.SlugField(blank=True, null=True, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.judul)
        super(Post, self).save(*args, **kwargs)
    
    def likes_hit(self):
        return self.likes.users.count()

    def dislikes_hit(self):
        return self.dis_likes.users.count()

    def bookmarks_hit(self):
        return self.bookmarks.count()

    def comments_hit(self):
        return self.comments.count()

    def __str__(self):
        return self.judul

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})



class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    reply = models.ForeignKey("Comment", related_name='replies', on_delete=models.CASCADE, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    activate = models.BooleanField(default=False)
    

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return "{} by {}".format(self.user.username, self.post)

    # def get_absolute_url(self):
    #     return reverse("Comment_detail", kwargs={"pk": self.pk})


class Like(models.Model):
    post = models.OneToOneField(Post, related_name="likes", on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='requirement_post_likes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.post.judul)


class DisLike(models.Model):
    post = models.OneToOneField(Post, related_name="dis_likes", on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='requirement_post_dis_likes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.post.judul)

project/podcast/forms.py
from django import forms

from .models import PodcastComment


class PodcastCommentForm(forms.ModelForm):
    
    class Meta:
        model = PodcastComment
        fields = ("body",)

project/podcast/views.py
from django.contrib import messages
from django.db.models import Count, Q
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from taggit.models import Tag

from .models import Podcast, PodcastComment, PodcastDisLike, PodcastKategori, PodcastLike
from .forms import PodcastCommentForm

# Create your views here.

class AllPodcast(ListView):
    model = Podcast
    template_name = 'podcast/podcast.html'
    context_object_name = 'podcasts'
    ordering = '-created'
    # paginate_by = 10

    def get_context_data(self, **kwargs):
        kategori_list = PodcastKategori.objects.all()
        self.kwargs.update({'kategori_list':kategori_list})

        user = self.request.user
        self.kwargs.update({'users':user})


        kwargs = self.kwargs
        context = super().get_context_data(**kwargs)
        context["title"] = "Podcast"
        context["active"] = "active"
        return context


class PodcastListView(ListView):
    model = Podcast
    template_name = "podcast/podcast.html"
    context_object_name = 'podcasts'
    ordering = "-created"
    # paginate_by = 10

    def get_queryset(self):
        b = PodcastKategori.objects.get(kategori=self.kwargs['kategori'])
        self.queryset = b.podcast_kategoris.all()
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        kategori_list = PodcastKategori.objects.all().exclude(kategori=self.kwargs['kategori'])
        self.kwargs.update({'kategori_list':kategori_list})

        kategori_active = PodcastKategori.objects.get(kategori=self.kwargs['kategori'])
        self.kwargs.update({'kategori_active':kategori_active})
        print(kategori_active)

        user = self.request.user
        self.kwargs.update({'users':user})


        kwargs = self.kwargs
        context = super().get_context_data(**kwargs)
        context["title"] = kategori_active
        context["active"] = "active"
        return context


class TagsPodcast(ListView):
    # model = Post
    template_name = "podcast/podcast.html"
    context_object_name = 'podcasts'
    ordering = '-created'
    # paginate_by = 10

    def get_queryset(self):
        self.queryset = Podcast.objects.filter(tags__name__contains=self.kwargs['tag'])
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        kategori_list = PodcastKategori.objects.all()
        self.kwargs.update({'kategori_list':kategori_list})

        user = self.request.user
        self.kwargs.update({'users':user})

        kategori_active = Tag.objects.get(name=self.kwargs['tag'])
        self.kwargs.update({'kategori_active':kategori_active})

        kwargs = self.kwargs
        context = super().get_context_data(**kwargs)
        context["title"] = kategori_active
        context["active"] = "active"
        return context


class PodcastDetailView(View):
    model = Podcast
    template_name = "podcast/single-podcast.html"
    comment_form = PodcastCommentForm()
    is_bookmarks = False
    is_archives = False


    def get(self, *args, **kwargs):
        podcast = self.model.objects.get(slug=self.kwargs['slug'])
        podcast.views = podcast.views+1
        podcast.save()

        if podcast.bookmark.filter(id=self.request.user.id):
            self.is_bookmarks = True;


        comments = podcast.podcast_comments.filter(activate=True, reply=None).order_by('-created')
        j_comments = podcast.podcast_comments.filter().order_by('-created')

        self.context = {
            'podcast':podcast,
            'comment_form':self.comment_form,
            'is_bookmarks': self.is_bookmarks,
            'comments':comments,
            'jumlah_comment': j_comments,
            'title':podcast,
        }
        return render(self.request, self.template_name, self.context)


class PodcastComment(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'next'
    model = PodcastComment

    def post(self, *args, **kwargs):
        podcast = Podcast.objects.get(slug=kwargs['slug'])
        podcast_comments = self.model.objects.filter(activate=True, reply=None).order_by('-created')
        if self.request.method == 'POST':
            self.comment_form = PodcastCommentForm(self.request.POST or None)
            if self.comment_form.is_valid():
                new_comment = self.comment_form.save(commit=False)
                reply_id = self.request.POST.get('reply')
                comment_qs = None
                if reply_id:
                    comment_qs = podcast.podcast_comments.get(id=reply_id)
                new_comment.reply = comment_qs
                new_comment.user = self.request.user
                new_comment.podcast = podcast
                new_comment.save()
                messages.success(self.request, "Komentar terkirin! sedang menunggu moderasi")
        return redirect('podcast:detail', kwargs['slug'])


class PodcastLikeDislike(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'next'

    def get(self, request, *args, **kwargs):
        # p = Post.objects.get(slug=kwargs['slug'])
        # print(p)
        podcast_id = self.kwargs.get('podcast_id', None)
        opinion = self.kwargs.get('opinion', None) #like atau dislike

        podcast = get_object_or_404(Podcast, id=podcast_id)

        try:
            podcast.podcast_dis_likes
        except Podcast.podcast_dis_likes.RelatedObjectDoesNotExist as identifier:
            PodcastDisLike.objects.create(podcast=podcast)

        try:
            podcast.podcast_likes
        except Podcast.podcast_likes.RelatedObjectDoesNotExist as identifier:
            PodcastLike.objects.create(podcast=podcast)

        if opinion.lower() == 'like':
            if request.user in podcast.podcast_likes.users.all():
                podcast.podcast_likes.users.remove(request.user)
            else:
                podcast.podcast_likes.users.add(request.user)
                podcast.podcast_dis_likes.users.remove(request.user)
        elif opinion.lower() == 'dis_like':
            if request.user in podcast.podcast_dis_likes.users.all():
                podcast.podcast_dis_likes.users.remove(request.user)
            else:
                podcast.podcast_dis_likes.users.add(request.user)
                podcast.podcast_likes.users.remove(request.user)
        else:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def podcast_bookmarks(request, id):
    podcast = get_object_or_404(Podcast, id=id)
    if podcast.bookmark.filter(id=request.user.id).exists():
        podcast.bookmark.remove(request.user)
    else:
        podcast.bookmark.add(request.user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def podcast_archives(request, id):
    podcast = get_object_or_404(Podcast, id=id)
    if podcast.archive.filter(id=request.user.id).exists():
        podcast.archive.remove(request.user)
    else:
        podcast.archive.add(request.user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



class PenulisPodcast(View):
    template_name='users/profile.html'

    def get(self, *args, **kwargs):
        users = User.objects.get(username=self.kwargs['user'])
        podcasts = users.podcasts.filter(publish=True)
        # likes = users.requirement_post_likes.all()
        # archives = users.archives.all()
        views_podcasts = users.podcasts.all()
        d = []
        for a in views_podcasts:
            b = a.views
            d.append(b)

        sum_views = sum(d)

        self.context = {
            'users':users,
            'sum_views':sum_views,
            'title':'Penulis Podcast',
            'podcasts': podcasts,
            # 'likes': likes,
            # 'archives': archives,
        }
        return render(self.request, self.template_name, self.context)

project/podcast/templates/podcast/podcast.html
{% extends 'base.html' %}
{% load static %}


{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/styles/category.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/styles/category_responsive.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/shadow.css' %}">
<link rel="stylesheet" href="{% static 'podcast/style.css' %}">
{% endblock extra_head %}

{% block header %}
<div class="home">
    <div class="home_background parallax-window" data-parallax="scroll" data-image-src="{% static 'blog/images/category.jpg' %}" data-speed="0.8"></div>
	<div class="home_content">
	{% for podcast in podcasts|slice:"1" %}
	<h2><b><a href="{#" style="color: white;">{{podcast.judul}}</a></b></h2>
	{% endfor %}
	{% if kategori_active %}
		<div class="post_category trans_200"><a href="{% url 'podcast:kategori' kategori_active %}" class="trans_200">{{kategori_active}}</a></div>
	{% else %}
		<div class="post_category trans_200"><a href="#" class="trans_200">All Post</a></div>
	{% endif %}
	</div>
</div>
{% endblock header %}

{% block contents %}
<!-- Main Content -->
<div class="col-lg-9">
	<div class="main_content">

		<!-- Category -->
		<div class="category">
			<div class="section_panel d-flex flex-row align-items-center justify-content-start">
				<div class="section_title">Kategori</div>
				<div class="section_tags ml-auto">
					<ul>
						<li class=""><a href="{% url 'podcast:home'%}">Semua</a></li>
						{% for k1 in kategori_list|slice:"4" %}
						<li><a href="{% url 'podcast:kategori' k1 %}">{{k1}}</a></li>
						{% endfor %}
					</ul>
				</div>
				<div class="section_panel_more">
					<ul>
						<li>more
							<ul>
								{% for k2 in kategori_list|slice:"4:" %}
								<li><a href="{% url 'podcast:kategori' k2 %}">{{k2}}</a></li>
								{% endfor %}
							</ul>
						</li>
					</ul>
				</div>
			</div>
			<div class="section_content">
                <div class="container">
					<div class="row poca-portfolio">
					{% for podcast in podcasts %}
						<div class="col-12 col-lg-12 single_gallery_item entre wow fadeInUp" data-wow-delay="0.2s">
							<!-- Welcome Music Area -->
							<div class="poca-music-area style-2 d-flex align-items-center flex-wrap">
								<div class="poca-music-content text-center">
									<span class="music-published-date mb-2">{{podcast.created}}</span>
									<div class="card-title">
                                        <a href="{% url 'podcast:detail' podcast.slug %}"><h2>{{podcast.judul}}</h2></a>
                                    </div>
									<div class="music-meta-data">
										<a href="{% url 'podcast:penulis' podcast.user.username %}">{{podcast.user.username}} </a>|<a href="#"> {{podcast.kategori}}</a>
									</div>
									<!-- Music Player -->
									<div class="poca-music-player">
										<audio preload="auto" controls>
										<source src="{{podcast.podcast.url}}">
										</audio>
									</div>
									<!-- Likes, Share & Download -->
									<div class="likes-share-download d-flex align-items-center justify-content-between mt-2">
										<div>
											<a href="{% url 'podcast:penulis' podcast.user.username %}" class="mr-3"><i class="fa fa-user" aria-hidden="true"></i> {{podcast.user.username}}</a>
											<span href="#" class="mr-3"><i class="fa fa-eye" aria-hidden="true"></i> {{podcast.views}}</span>
											<span class="pointer">
												{% if request.user in podcast.podcast_likes.users.all%}
												<!-- already liked-->
												<a href={% url 'podcast:like_dislike' podcast_id=podcast.pk opinion='like' %}> <i
												data-toggle="tooltip" data-placement="bottom" title="Unlike"
												class="like fa fa-heart pr-2" style="color: red;">
												<span>{{podcast.podcast_likes_hint}}</span>
												</i>
												</a>
												{% else %}
												<!--not liked-->
												<a href={% url 'podcast:like_dislike' podcast_id=podcast.pk opinion='like' %}><i
												data-toggle="tooltip" data-placement="bottom" title="Like"
												class="default-icon fa fa-heart pr-2">
												<span>{% if podcast.podcast_likes  %}{{podcast.podcast_likes_hint}} {% else %} 0
												{% endif %}</span></i>
												</a>
												{% endif %}
											</span>
										</div>
										<div>
											<span href="#" class="mr-3"><i class="fa fa-comments" aria-hidden="true"></i> {{podcast.podcast_comments_hint}}</span>
											{% if request.user in podcast.bookmark.all %}
											<a href="{% url 'podcast:bookmarks' podcast.id %}" style="color: red;"><i class="fa fa-bookmark" aria-hidden="true" style="color: red;"></i> {{podcast.bookmark_hint}}</a>
											{% else %}
											<a href="{% url 'podcast:bookmarks' podcast.id %}"><i class="fa fa-bookmark" aria-hidden="true"></i> {{podcast.bookmark_hint}}</a>
											{% endif %}
										</div>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="load_more">
		<div id="load_more" class="load_more_button text-center trans_200">Load More</div>
	</div>
</div>
{% endblock contents %}

{% block sidebar %}
{% include 'snippets/sidebar.html' %}
{% endblock sidebar %}

{% block extra_body %}
<script src="{% static 'blog/js/category.js' %}"></script>
<script src="{% static 'podcast/js/poca.bundle.js' %}"></script>
<script src="{% static 'podcast/js/default-assets/active.js' %}"></script>
{% endblock extra_body %}