project/blog/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import PostListView, PostDetailView, LikeDislike, Comment, bookmarks, Penulis, archives, AllPost, Tags, search

app_name = "blog"

urlpatterns = [
    path('', AllPost.as_view(), name='home'),
    path('videos/', TemplateView.as_view(template_name='blog/videos.html'), name='videos'),
    path('post/<slug>/', PostDetailView.as_view(), name='detail'),
    path('tags/<str:tag>', Tags.as_view(), name='tag'),
    path('search/',search, name='search' ),
    path('requirement/<int:post_id>/<str:opinion>', LikeDislike.as_view(), name='like_dislike'),
    path('comment/<str:slug>', Comment.as_view(), name='comment'),
    path('video-detail/', TemplateView.as_view(template_name='blog/single-video.html'), name='video-detail'),
    path('bookmarks/<int:id>', bookmarks, name='bookmarks'),
    path('archives/<int:id>', archives, name='archives'),
    path('penulis/<str:user>', Penulis.as_view(), name='penulis'),
    path('profile/', TemplateView.as_view(template_name='blog/profile.html'), name='profile'),
    path('<kategori>/', PostListView.as_view(), name='kategori'),
]

project/risset/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_view
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from .views import home
# from .admin import admin_site

admin.autodiscover()

urlpatterns = [
    path('', home, name='home'),
    path('home/', TemplateView.as_view(template_name='index.html'), name='home'),
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('password-reset/', auth_view.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_view.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_view.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('dashboard/', TemplateView.as_view(template_name='users/dashboard.html'), name='dashboard'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('podcast/', include('podcast.urls', namespace='podcast')),
    path('users/', include('users.urls', namespace='users')),
    path('video/', include('video.urls', namespace='video')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import register, activate, Profile, Bookmarks,  Follow, tambah_artikel, update_artikel, delete_artikel
app_name="users"

urlpatterns = [
    path('', Profile, name='profile'),
    path('follow/<user_id>', Follow.as_view(), name='follow'),
    path('tambah-artikel/', tambah_artikel, name="tambah-artikel"),
    path('update-artikel/<int:id>', update_artikel, name="update-artikel"),
    path('delete-artikel/<int:id>', delete_artikel, name="delete-artikel"),
    path('register/', register, name='register'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('bookmark/', Bookmarks.as_view(), name='bookmark'),
]

project/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse
from django.conf import settings
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.

class Kategori(models.Model):
    kategori = models.CharField(max_length=125)

    def __str__(self):
        return self.kategori


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    judul = models.CharField(max_length=125)
    thumbnail = models.ImageField(upload_to='blog/post')
    kategori = models.ForeignKey(Kategori, on_delete=models.CASCADE, blank=True, null=True, related_name='kategoris')
    tags = TaggableManager(blank=True)
    atrikel = RichTextUploadingField(blank=True, null=True, config_name='default')
    views = models.PositiveIntegerField(default=0)
    bookmarks = models.ManyToManyField(User, related_name='bookmarks', blank=True)
    archive = models.ManyToManyField(User, related_name="archives", blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    publish = models.BooleanField(default=False, editable=False)
    slug = models.SlugField(blank=True, null=True, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.judul)
        super(Post, self).save(*args, **kwargs)
    
    def likes_hit(self):
        return self.likes.users.count()

    def dislikes_hit(self):
        return self.dis_likes.users.count()

    def bookmarks_hit(self):
        return self.bookmarks.count()

    def comments_hit(self):
        return self.comments.count()

    def __str__(self):
        return self.judul

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})



class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    reply = models.ForeignKey("Comment", related_name='replies', on_delete=models.CASCADE, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    activate = models.BooleanField(default=False)
    

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return "{} by {}".format(self.user.username, self.post)

    # def get_absolute_url(self):
    #     return reverse("Comment_detail", kwargs={"pk": self.pk})


class Like(models.Model):
    post = models.OneToOneField(Post, related_name="likes", on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='requirement_post_likes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.post.judul)


class DisLike(models.Model):
    post = models.OneToOneField(Post, related_name="dis_likes", on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='requirement_post_dis_likes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.post.judul)

project/blog/forms.py
from django import forms

from .models import Comment, Post


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ("body",)

project/blog/views.py
from django.contrib import messages
from django.db.models import Count, Q
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from taggit.models import Tag

from .models import Post, Comment, Like, DisLike, Kategori
from podcast.models import Podcast
from .forms import CommentForm

class AllPost(ListView):
    model = Post
    template_name = 'blog/blog.html'
    context_object_name = 'posts'
    ordering = '-created'
    # paginate_by = 10

    def get_context_data(self, **kwargs):
        kategori_list = Kategori.objects.all()
        self.kwargs.update({'kategori_list':kategori_list})

        user = self.request.user
        self.kwargs.update({'users':user})


        kwargs = self.kwargs
        context = super().get_context_data(**kwargs)
        context["title"] = "Blog"
        context["active"] = "active"
        return context


class PostListView(ListView):
    model = Post
    template_name = "blog/blog.html"
    context_object_name = 'posts'
    ordering = "-created"
    # paginate_by = 10

    def get_queryset(self):
        b = Kategori.objects.get(kategori=self.kwargs['kategori'])
        self.queryset = b.kategoris.all()
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        kategori_list = Kategori.objects.all().exclude(kategori=self.kwargs['kategori'])
        self.kwargs.update({'kategori_list':kategori_list})

        kategori_active = Kategori.objects.get(kategori=self.kwargs['kategori'])
        self.kwargs.update({'kategori_active':kategori_active})
        print(kategori_active)

        user = self.request.user
        self.kwargs.update({'users':user})


        kwargs = self.kwargs
        context = super().get_context_data(**kwargs)
        context["title"] = kategori_active
        context["active"] = "active"
        return context


class Tags(ListView):
    # model = Post
    template_name = "blog/blog.html"
    context_object_name = 'posts'
    # ordering = '-created'
    # paginate_by = 10

    def get_queryset(self):
        self.queryset = Post.objects.filter(tags__name__contains=self.kwargs['tag'])
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        kategori_list = Kategori.objects.all()
        self.kwargs.update({'kategori_list':kategori_list})

        user = self.request.user
        self.kwargs.update({'users':user})

        kategori_active = Tag.objects.get(name=self.kwargs['tag'])
        self.kwargs.update({'kategori_active':kategori_active})

        kwargs = self.kwargs
        context = super().get_context_data(**kwargs)
        context["title"] = kategori_active
        context["active"] = "active"
        return context


def search(request):
    if request.method == 'GET':
        query = request.GET.get('q')
        submitbutton = request.GET.get('submit')
        if query is not None:
            lookups = Q(judul__icontains=query) | Q(
                tags__name__icontains=query) | Q(kategori__kategori__icontains=query) | Q(slug__icontains=query) | Q(user__username__icontains=query)

            posts = Post.objects.filter(lookups).distinct() and Podcast.objects.filter(lookups).distinct()
            kategori_list = Kategori.objects.all() 

            context = {
                'posts': posts,
                'submitbutton': submitbutton,
                'kategori_list':kategori_list,
                'title':'Search',
                'kategori_active': 'Search'
            }
            return render(request, 'blog/search.html', context)
        else:
            return render(request, 'blog/search.html')
    else:
        return render(request, 'blog/search.html')
    


class PostDetailView(View):
    model = Post
    template_name = "blog/detail.html"
    comment_form = CommentForm()
    is_bookmarks = False
    is_archives = False


    def get(self, *args, **kwargs):
        post = self.model.objects.get(slug=self.kwargs['slug'])
        post.views = post.views+1
        post.save()

        if post.bookmarks.filter(id=self.request.user.id):
            self.is_bookmarks = True;


        comments = post.comments.filter(activate=True, reply=None).order_by('-created')
        j_comments = post.comments.filter().order_by('-created')

        self.context = {
            'post':post,
            'comment_form':self.comment_form,
            'is_bookmarks': self.is_bookmarks,
            'comments':comments,
            'jumlah_comment': j_comments,
            'title':post,
        }
        return render(self.request, self.template_name, self.context)

class Comment(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'next'
    model = Comment

    def post(self, *args, **kwargs):
        post = Post.objects.get(slug=kwargs['slug'])
        comments = self.model.objects.filter(activate=True, reply=None).order_by('-created')
        if self.request.method == 'POST':
            self.comment_form = CommentForm(self.request.POST or None)
            if self.comment_form.is_valid():
                new_comment = self.comment_form.save(commit=False)
                reply_id = self.request.POST.get('reply')
                comment_qs = None
                if reply_id:
                    comment_qs = post.comments.get(id=reply_id)
                new_comment.reply = comment_qs
                new_comment.user = self.request.user
                new_comment.post = post
                new_comment.save()
                messages.success(self.request, "Komentar terkirin! sedang menunggu moderasi")
        return redirect('blog:detail', kwargs['slug'])


class LikeDislike(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'next'

    def get(self, request, *args, **kwargs):
        # p = Post.objects.get(slug=kwargs['slug'])
        # print(p)
        post_id = self.kwargs.get('post_id', None)
        opinion = self.kwargs.get('opinion', None) #like atau dislike

        post = get_object_or_404(Post, id=post_id)

        try:
            post.dis_likes
        except Post.dis_likes.RelatedObjectDoesNotExist as identifier:
            DisLike.objects.create(post=post)

        try:
            post.likes
        except Post.likes.RelatedObjectDoesNotExist as identifier:
            Like.objects.create(post=post)

        if opinion.lower() == 'like':
            if request.user in post.likes.users.all():
                post.likes.users.remove(request.user)
            else:
                post.likes.users.add(request.user)
                post.dis_likes.users.remove(request.user)
        elif opinion.lower() == 'dis_like':
            if request.user in post.dis_likes.users.all():
                post.dis_likes.users.remove(request.user)
            else:
                post.dis_likes.users.add(request.user)
                post.likes.users.remove(request.user)
        else:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def bookmarks(request, id):
    post = get_object_or_404(Post, id=id)
    if post.bookmarks.filter(id=request.user.id).exists():
        post.bookmarks.remove(request.user)
    else:
        post.bookmarks.add(request.user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def archives(request, id):
    post = get_object_or_404(Post, id=id)
    if post.archive.filter(id=request.user.id).exists():
        post.archive.remove(request.user)
    else:
        post.archive.add(request.user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class Penulis(View):
    template_name='users/profile.html'

    def get(self, *args, **kwargs):
        users = User.objects.get(username=self.kwargs['user'])
        posts = users.posts.filter(publish=True)
        likes = users.requirement_post_likes.all()
        archives = users.archives.all()
        views_post = users.posts.all()
        d = []
        for a in views_post:
            b = a.views
            d.append(b)

        sum_views = sum(d)

        self.context = {
            'users':users,
            'sum_views':sum_views,
            'title':'Penulis',
            'posts': posts,
            'likes': likes,
            'archives': archives,
        }
        return render(self.request, self.template_name, self.context)

project/blog/templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/styles/category.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/styles/category_responsive.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/shadow.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/post-meta.css' %}">
{% endblock extra_head %}

{% block header %}
	<div class="home">
		<div class="home_background parallax-window" data-parallax="scroll" data-image-src="{% static 'blog/images/sunset.jpg' %}" data-speed="0.2"></div>
		<div class="home_content">
		{% for post in posts|slice:"1" %}
		<h2><b><a href="{% url 'blog:detail' post.slug %}" style="color: white;">{{post.judul}}</a></b></h2>
		{% endfor %}
		{% if kategori_active %}
			<div class="post_category trans_200"><a href="{% url 'blog:kategori' kategori_active %}" class="trans_200">{{kategori_active}}</a></div>
		{% else %}
			<div class="post_category trans_200"><a href="#" class="trans_200">All Post</a></div>
		{% endif %}
		</div>
	</div>
{% endblock header %}

{% block contents %}
<!-- Main Content -->
<div class="col-lg-9">
	<div class="main_content">
		<!-- Category -->
		<div class="category">
			<div class="section_panel d-flex flex-row align-items-center justify-content-start">
				<div class="section_title">Kategori</div>
				<div class="section_tags ml-auto">
					<ul>
						<li class=""><a href="{% url 'blog:home'%}">Semua</a></li>
						{% for k1 in kategori_list|slice:"4" %}
						<li class=""><a href="{% url 'blog:kategori' k1 %}">{{k1}}</a></li>
						{% endfor %}
					</ul>
				</div>
				<div class="section_panel_more">
					<ul>
						<li>more
							<ul>
								{% for k2 in kategori_list|slice:"4:" %}
								<li><a href="{% url 'blog:kategori' k2 %}">{{k2}}</a></li>
								{% endfor %}
							</ul>
						</li>
					</ul>
				</div>
			</div>
			<div class="section_content">
				<div class="grid clearfix">

					<!-- Largest Card With Image -->
					{% for post in posts|slice:"1:7" %}
					<div class="card card_largest_with_image grid-item s_dow">
						<img class="card-img-top" src="{{post.thumbnail.url}}" alt="" style="height: 250px;">
						<div class="card-body">
							<div class="card-title"><a href="{% url 'blog:detail' post.slug %}">{{post.judul}}</a></div>
							<p class="card-text">{{post.atrikel|safe|truncatewords:"20"}}</p>
							<div class="likes-share-download d-flex align-items-center justify-content-between mt-2">
								<div>
									<a href="{% url 'blog:penulis' post.user.username %}" class="mr-3"><i class="fa fa-user" aria-hidden="true"></i> {{post.user.username}}</a>
									<span href="#" class="mr-3"><i class="fa fa-eye" aria-hidden="true"></i> {{post.views}}</span>
									<span class="pointer">
										{% if request.user in post.likes.users.all%}
										<!-- already liked-->
										<a href={% url 'blog:like_dislike' post_id=post.pk opinion='like' %}> <i
										data-toggle="tooltip" data-placement="bottom" title="Unlike"
										class="like fa fa-heart pr-2" style="color: red;">
										<span>{{post.likes_hit}}</span>
										</i>
										</a>
										{% else %}
										<!--not liked-->
										<a href={% url 'blog:like_dislike' post_id=post.pk opinion='like' %}><i
										data-toggle="tooltip" data-placement="bottom" title="Like"
										class="default-icon fa fa-heart pr-2">
										<span>{% if post.likes  %}{{post.likes_hit}} {% else %} 0
										{% endif %}</span></i>
										</a>
										{% endif %}
									</span>
								</div>
								<div>
									<span href="#" class="mr-3"><i class="fa fa-comments" aria-hidden="true"></i> {{post.comments_hit}}</span>
									{% if request.user in post.bookmarks.all %}
									<a href="{% url 'blog:bookmarks' post.id %}" style="color: red;"><i class="fa fa-bookmark" aria-hidden="true" style="color: red;"></i> {{post.bookmarks_hit}}</a>
									{% else %}
									<a href="{% url 'blog:bookmarks' post.id %}"><i class="fa fa-bookmark" aria-hidden="true"></i> {{post.bookmarks_hit}}</a>
									{% endif %}
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
					
					<!-- Small Card Without Image -->
					
					{% for post in posts|slice:"7:" %}
					<div class="card card_default card_small_no_image grid-item s_dow">
						<div class="card-body">
							<div class="card-title card-title-small"><a href="{% url 'blog:detail' post.slug %}">{{post.judul}}</a></div>
							<div class="likes-share-download d-flex align-items-center justify-content-between mt-2">
								<div>
									<a href="{% url 'blog:penulis' post.user.username %}" class="mr-3"><i class="fa fa-user" aria-hidden="true"></i> {{post.user.username}}</a>
									<span class="pointer">
										{% if request.user in post.likes.users.all%}
										<!-- already liked-->
										<a href={% url 'blog:like_dislike' post_id=post.pk opinion='like' %}> <i
										data-toggle="tooltip" data-placement="bottom" title="Unlike"
										class="like fa fa-heart pr-2" style="color: red;">
										<span>{{post.likes_hit}}</span>
										</i>
										</a>
										{% else %}
										<!--not liked-->
										<a href={% url 'blog:like_dislike' post_id=post.pk opinion='like' %}><i
										data-toggle="tooltip" data-placement="bottom" title="Like"
										class="default-icon fa fa-heart pr-2">
										<span>{% if post.likes  %}{{post.likes_hit}} {% else %} 0
										{% endif %}</span></i>
										</a>
										{% endif %}
									</span>
								</div>
								<div>
									{% if request.user in post.bookmarks.all %}
									<a href="{% url 'blog:bookmarks' post.id %}" style="color: red;"><i class="fa fa-bookmark" aria-hidden="true" style="color: red;"></i> {{post.bookmarks_hit}}</a>
									{% else %}
									<a href="{% url 'blog:bookmarks' post.id %}"><i class="fa fa-bookmark" aria-hidden="true"></i> {{post.bookmarks_hit}}</a>
									{% endif %}
								</div>
							</div>
						</div>
					</div>
					{% endfor %}

					<div class="card card_default card_small_no_image grid-item s_dow">
						<div class="card-body">
							<div class="card-title card-title-small"><a href="post.html">Risset Meroket, Sampai Ke Belahan Dunia</a></div>
							<div class="likes-share-download d-flex align-items-center justify-content-between mt-2">
								<div>
									<a href="#" class="mr-3"><i class="fa fa-user" aria-hidden="true"></i> Danang Haris</a>
									<a href="#" class=""><i class="fa fa-heart" aria-hidden="true"></i> 130</a>
								</div>
								<div>
									<a href="#"><i class="fa fa-bookmark" aria-hidden="true"></i> 50</a>
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
	<div class="load_more">
		<div id="load_more" class="load_more_button text-center trans_200">Load More</div>
	</div>
</div>
{% endblock contents %}

{% block sidebar %}
{% include 'snippets/sidebar.html' %}
{% endblock sidebar %}

{% block extra_body %}
<script src="{% static 'blog/js/category.js' %}"></script>
{% endblock extra_body %}

project/blog/templates/blog/search.html
{% extends 'base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/styles/category.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/styles/category_responsive.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/shadow.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/post-meta.css' %}">
{% endblock extra_head %}

{% block header %}
	<div class="home">
		<div class="home_background parallax-window" data-parallax="scroll" data-image-src="{% static 'blog/images/category.jpg' %}" data-speed="0.8"></div>
		<div class="home_content">
		{% if kategori_active %}
			<div class="post_category trans_200"><a href="{% url 'blog:kategori' kategori_active %}" class="trans_200">{{kategori_active}}</a></div>
		{% else %}
			<div class="post_category trans_200"><a href="#" class="trans_200">All Post</a></div>
		{% endif %}
		</div>
	</div>
	</div>
{% endblock header %}

{% block contents %}
<!-- Main Content -->
<div class="col-lg-9">
	<div class="main_content">
		<!-- Category -->
		<div class="category">
			<div class="section_panel d-flex flex-row align-items-center justify-content-start">
				<div class="section_title">Kategori</div>
				<div class="section_tags ml-auto">
					<ul>
						<li class=""><a href="{% url 'blog:home'%}">Semua</a></li>
						{% for k1 in kategori_list|slice:5 %}
						<li class=""><a href="{% url 'blog:kategori' k1 %}">{{k1}}</a></li>
						{% endfor %}
					</ul>
				</div>
				<div class="section_panel_more">
					<ul>
						<li>more
							<ul>
								{% for k2 in kategori_list|slice:"5:" %}
								<li><a href="{% url 'blog:kategori' k2 %}">{{k2}}</a></li>
								{% endfor %}
							</ul>
						</li>
					</ul>
				</div>
			</div>
			<div class="section_content">
            {% if submitbutton == request.GET.q != '' %}
                {% if posts %}
                <h3>Hasil pencarian dari <b>{{ request.GET.q }}</b></h3>
                <br/><br/>
					{% for post in posts|slice:"10" %}
					<div class="card card_largest_with_image grid-item s_dow">
						<img class="card-img-top" src="{{post.thumbnail.url}}" alt="" style="height: 250px;">
						<div class="card-body">
							<div class="card-title"><a href="{% url 'blog:detail' post.slug %}">{{post.judul}}</a></div>
							<p class="card-text">{{post.atrikel|safe|truncatewords:"20"}}</p>
							<div class="likes-share-download d-flex align-items-center justify-content-between mt-2">
								<div>
									<a href="{% url 'blog:penulis' post.user.username %}" class="mr-3"><i class="fa fa-user" aria-hidden="true"></i> {{post.user.username}}</a>
									<a href="#" class="mr-3"><i class="fa fa-eye" aria-hidden="true"></i> {{post.views}}</a>
									<span class="pointer">
										{% if request.user in post.likes.users.all%}
										<!-- already liked-->
										<a href={% url 'blog:like_dislike' post_id=post.pk opinion='like' %}> <i
										data-toggle="tooltip" data-placement="bottom" title="Unlike"
										class="like fa fa-heart pr-2" style="color: red;">
										<span>{{post.likes_hit}}</span>
										</i>
										</a>
										{% else %}
										<!--not liked-->
										<a href={% url 'blog:like_dislike' post_id=post.pk opinion='like' %}><i
										data-toggle="tooltip" data-placement="bottom" title="Like"
										class="default-icon fa fa-heart pr-2">
										<span>{% if post.likes  %}{{post.likes_hit}} {% else %} 0
										{% endif %}</span></i>
										</a>
										{% endif %}
									</span>
								</div>
								<div>
									<span href="#" class="mr-3"><i class="fa fa-comments" aria-hidden="true"></i> {{post.comments_hit}}</span>
									{% if request.user in post.bookmarks.all %}
									<a href="{% url 'blog:bookmarks' post.id %}" style="color: red;"><i class="fa fa-bookmark" aria-hidden="true" style="color: red;"></i> {{post.bookmarks_hit}}</a>
									{% else %}
									<a href="{% url 'blog:bookmarks' post.id %}"><i class="fa fa-bookmark" aria-hidden="true"></i> {{post.bookmarks_hit}}</a>
									{% endif %}
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
                {% else %}
                <h3>Hasil dari <b>{{ request.GET.q }}</b> tidak ditemukan! </h3>
                {% endif %}
                {% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock contents %}

{% block sidebar %}
{% include 'snippets/sidebar.html' %}
{% endblock sidebar %}

{% block extra_body %}
<script src="{% static 'blog/js/category.js' %}"></script>
{% endblock extra_body %}